GOCMD?= go
COVER_PKGS := $(shell go list ./... | tr "\n" ",")
LINT := golangci-lint
MULTIMOD := $(GOCMD) run go.opentelemetry.io/build-tools/multimod

.PHONY: tests
test:
	$(GOCMD) test ./...

.PHONY: test-with-cover
test-with-cover:
	mkdir -p $(PWD)/coverage/unit
	$(GOCMD) test -cover -covermode=atomic -coverpkg $(COVER_PKGS) -test.gocoverdir="$(PWD)/coverage/unit" ./...

.PHONY: lint
lint:
	$(LINT) run

.PHONY: tidy
tidy:
	rm -fr go.sum
	$(GOCMD) mod tidy
